publish_external: false
validation_policy: silver

generators:
  jsonld_context: true
  shacl: true
  shacl_flags: ""
  python: true
  java: true
  json_schema: true
  owl: true
  owl_flags: ""
  rdf: true
  protobuf: true
  graphql: false
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: false
  xsd: false
  openapi: false
  asyncapi: false
