FROM docker.io/squidfunk/mkdocs-material:9.7

# Build format: Docker v2 (via --format docker flag in Makefile)
RUN pip install --no-cache-dir \
    mkdocs-kroki-plugin \
    mkdocs-build-cache-plugin
