publish_external: false
validation_policy: gold

generators:
  jsonld_context: true
  shacl: true
  shacl_flags: ""
  python: true
  json_schema: true
  owl: true
  owl_flags: ""
  rdf: true
  protobuf: true
  graphql: false
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: false
