publish_external: false
validation_policy: silver
external_spec_url: https://informasjonsmodell.felleskomponent.no/docs/package_personvern?v=v4.0.30
external_spec_label: FINT Informasjonsmodell - Personvern
generators:
  jsonld_context: false
  shacl: false
  shacl_flags: "--exclude-imports"
  python: false
  json_schema: true
  owl: true
  rdf: true
  protobuf: false
  graphql: false
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: true
  xsd: false
  openapi: false
  asyncapi: false
