publish_external: false
validation_policy: gold
external_spec_url: https://informasjonsforvaltning.github.io/dqv-ap-no/
external_spec_label: "DQV-AP-NO (Norsk applikasjonsprofil av DQV)"

generators:
  jsonld_context: false
  shacl: true
  python: false
  json_schema: false
  owl: true
  rdf: true
  protobuf: false
  graphql: false
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: false
  xsd: false
  openapi: false
  asyncapi: false
