name: Generer schema.json
description: Køyrer gen-json-schema for alle skjema i domenet

inputs:
  domain:
    description: Domenenamn (ap-no, fair, fint, ngr, oreg, samt)
    required: true

runs:
  using: composite
  steps:
    - name: Generer schema.json
      shell: bash
      run: make domain-gen-json-schema DOMAIN=${{ inputs.domain }}
