publish_external: true
validation_policy: bronze

generators:
  jsonld_context: false
  shacl: false
  python: false
  json_schema: false
  owl: false
  rdf: true
  protobuf: false
  graphql: false
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: false
  xsd: false
  openapi: false
  asyncapi: false
