name: Generer ontology.ttl (OWL)
description: Køyrer gen-owl for alle skjema i domenet

inputs:
  domain:
    description: Domenenamn (ap-no, fair, fint, ngr, oreg, samt)
    required: true

runs:
  using: composite
  steps:
    - name: Generer ontology.ttl (OWL)
      shell: bash
      run: make domain-gen-owl DOMAIN=${{ inputs.domain }}
