name: Last inn container-images
description: Last ned og load linkml-local og python-pytest images frå workflow-artefaktar

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: linkml-local-image

    - uses: actions/download-artifact@v4
      with:
        name: python-pytest-image

    - name: Last inn images
      shell: bash
      run: |
        podman load < <(zstd -d -c linkml-local.tar.zst)
        podman load < <(zstd -d -c python-pytest.tar.zst)
