name: Last inn container-images
description: Hent linkml-local og python-pytest images frå GHCR

runs:
  using: composite
  steps:
    - name: Logg inn på GHCR
      shell: bash
      run: echo "${{ github.token }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Hent images frå GHCR
      shell: bash
      run: |
        podman pull ghcr.io/${{ github.repository_owner }}/linkml-local:${{ hashFiles('src/assets/containers/Dockerfile.linkml') }}
        podman pull ghcr.io/${{ github.repository_owner }}/python-pytest:${{ hashFiles('src/assets/containers/Dockerfile.python', 'src/assets/containers/requirements-python-test.txt') }}
        podman tag ghcr.io/${{ github.repository_owner }}/linkml-local:${{ hashFiles('src/assets/containers/Dockerfile.linkml') }} localhost/linkml-local:latest
        podman tag ghcr.io/${{ github.repository_owner }}/python-pytest:${{ hashFiles('src/assets/containers/Dockerfile.python', 'src/assets/containers/requirements-python-test.txt') }} localhost/python-pytest:latest
