publish_external: false
validation_policy: gold
external_spec_url: https://informasjonsforvaltning.github.io/cpsv-ap-no/
external_spec_label: "Spesifikasjon for tjeneste- og hendelsesbeskrivelser (CPSV-AP-NO)"

generators:
  jsonld_context: false
  shacl: true
  python: false
  json_schema: false
  owl: true
  rdf: true
  protobuf: false
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: false
  xsd: false
  openapi: false
  asyncapi: false
