publish_external: false
validation_policy: silver
external_spec_url: https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/

generators:
  jsonld_context: false
  shacl: true
  python: false
  json_schema: true
  owl: true
  rdf: true
  protobuf: false
  graphql: false
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: false
  xsd: true
  openapi: false
  asyncapi: false
