publish_external: false
validation_policy: silver

generators:
  # Artefaktgeneratorer
  jsonld_context: false
  shacl: true
  shacl_flags: ""
  python: false
  json_schema: true
  owl: true
  owl_flags: ""
  rdf: true
  protobuf: false
  example_rdf: false
  openapi: false
  graphql: false
  xsd: true
  asyncapi: false

  # Dokumentasjonsgeneratorer
  erdiagram: true
  docs: true
  plantuml: true
