publish_external: false
validation_policy: silver
external_spec_url: https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/

generators:
  jsonld_context: true
  shacl: true
  python: true
  json_schema: true
  owl: true
  rdf: true
  protobuf: true
  erdiagram: true
  docs: true
  plantuml: true
  example_rdf: true
  xsd: false
  openapi: true
  asyncapi: false
