publish_external: false
validation_policy: bronze

# Metadata for aggregering til begrepskatalog
# aggregation-metadata vert auto-detektert frå CODEOWNERS.md basert på path-matching
# (kan overstyrast ved å legge til eksplisitt aggregation-blokk her)

generators:
  jsonld_context: false
  shacl: false
  python: false
  json_schema: false
  owl: false
  rdf: false
  protobuf: false
  erdiagram: false
  docs: false
  plantuml: false
  example_rdf: false
